# project-mkdocs/docker-compose.yml
# version: '3.8'

services:
  mkdocs:
    build: .      
    # build: . 和image这个官方镜像冲突了，
    # image: squidfunk/mkdocs-material
    ports:
      - "8000:8000"
    volumes:
      - .:/docs
    command: mkdocs serve -a 0.0.0.0:8000
    restart: unless-stopped